apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-visit-processing
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: app-policies
    - name: infrastructure-security
    - name: infrastructure-data-postgres
    - name: infrastructure-data-kafka
  sourceRef:
    kind: GitRepository
    name: dev-repo
  path: ./kubernetes/apps/base/visit-processing
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: visit-processor
      namespace: flux-system
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: visit-demo-db
      namespace: visit-processing
  timeout: 15m
