stages:
  - tofu_check
  - ansible_check
  - tofu_plan
  - tofu_apply
  - ansible_inventory
  - ansible_smoke
  - ansible_base
  - ansible_runtime
  - ansible_bootstrap
  - ansible_flux
  - tofu_destroy

include:
  - local: ".gitlab/ci/opentofu.yml"
  - local: ".gitlab/ci/ansible.yml"
