version: "3"

dotenv:
  - .env

vars:
  PROJECT_DIR:
    sh: pwd -P
  OUTPUTS: infra/outputs.json
  INVENTORY: ansible/inventories/dev/hosts.yml
  ANSIBLE_CONFIG_FILE: ansible/ansible.cfg
  VENV_PYTHON: .venv/bin/python3
  VENV_ANSIBLE: .venv/bin/ansible
  VENV_ANSIBLE_GALAXY: .venv/bin/ansible-galaxy
  VENV_ANSIBLE_PLAYBOOK: .venv/bin/ansible-playbook
  VENV_ANSIBLE_INVENTORY: .venv/bin/ansible-inventory
  KUBECONFIG_FILE: "{{.PROJECT_DIR}}/kubeconfig.dev"

includes:
  ansible: .taskfiles/ansible.yml
  env: .taskfiles/env.yml
  ingress: .taskfiles/ingress.yml
  openbao: .taskfiles/openbao.yml
  pipeline: .taskfiles/pipeline.yml
  tofu: .taskfiles/tofu.yml
  venv: .taskfiles/venv.yml
