---
rke2_cilium_manifest_path: /var/lib/rancher/rke2/server/manifests/rke2-cilium-config.yaml
rke2_cilium_gateway_bootstrap_rbac_path: /var/lib/rancher/rke2/server/manifests/cilium-gateway-bootstrap-rbac.yaml
rke2_gateway_api_standard_manifest_path: /var/lib/rancher/rke2/server/manifests/gateway-api-standard.yaml
rke2_gateway_api_experimental_manifest_path: /var/lib/rancher/rke2/server/manifests/gateway-api-experimental.yaml
rke2_gateway_api_standard_manifest_url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/standard-install.yaml
rke2_gateway_api_standard_manifest_checksum: sha256:73b91b77f6be023a8c92c969fc664e5bd3b1a28aea59eac9ebc904607354dad2
rke2_kubeconfig_path: /etc/rancher/rke2/rke2.yaml
rke2_kubectl_path: /var/lib/rancher/rke2/bin/kubectl
