apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - kustomization-platform-core.yaml
  - kustomization-platform-scheduling-policies.yaml
  - kustomization-platform-data-ceph.yaml
