apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-data-postgres
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-repo
  path: ./kubernetes/platform/dev/data-platform/services/postgres
  prune: true
  wait: true
  timeout: 15m
