---
rke2_kubeconfig_path: /etc/rancher/rke2/rke2.yaml
rke2_kubectl_path: /var/lib/rancher/rke2/bin/kubectl
rke2_gateway_worker_label: "node-role.kubernetes.io/worker=true"
cluster_validate_retries: 60
cluster_validate_delay: 10
cluster_validate_expected_nodes: 6
