apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: visit-web
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/example/visit-ui
  secretRef:
    name: ghcr-registry
