apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: visit-web
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: dev-repo
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: flux-bot@users.noreply.github.com
      messageTemplate: "flux(image): update visit-web images"
    push:
      branch: main
  update:
    path: ./kubernetes/apps/dev/visit-web
    strategy: Setters
