apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: visit-web
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: visit-web
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/visit-ui
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: dev-repo
  values:
    imagePullSecrets:
      - name: ghcr-pull
    env:
      visitGatewayUrl: http://visit-web-visit-gateway/api
    image:
      repository: ghcr.io/martin3398/visit-ui # {"$imagepolicy": "flux-system:visit-web:name"}
      tag: 20260630225005-183b2ff8 # {"$imagepolicy": "flux-system:visit-web:tag"}
