apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: visit-gateway
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/martin3398/visit-gateway
  secretRef:
    name: ghcr-registry
