apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-web.yaml
  - externalsecret-web.yaml
  - externalsecret-kafka.yaml
  - helmrelease-visit-web.yaml

  - helmrelease-visit-gateway.yaml
  - imagerepository-visit-web.yaml
  - imagepolicy-visit-web.yaml
  - imagerepository-visit-gateway.yaml
  - imagepolicy-visit-gateway.yaml
  - imageupdateautomation.yaml
