apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-user
  namespace: data-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: app-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: dev/platform/postgres/app-user
        property: username
    - secretKey: password
      remoteRef:
        key: dev/platform/postgres/app-user
        property: password
