apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kafka-exporter-tls
  namespace: data-kafka
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-data-kafka
  target:
    name: kafka-exporter-tls
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: kafka-cluster-ca-cert
        property: ca.crt
    - secretKey: user.crt
      remoteRef:
        key: kafka-exporter
        property: user.crt
    - secretKey: user.key
      remoteRef:
        key: kafka-exporter
        property: user.key
