apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - kustomization-platform-core.yaml
  - kustomization-platform-apps.yaml
  - kustomization-platform-ingress.yaml
  - kustomization-platform-observability.yaml
  - kustomization-platform-data-ceph.yaml
  - kustomization-platform-data-services.yaml
  - kustomization-app-visit-web.yaml
  - kustomization-app-visit-processing.yaml
