apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server
  - operators/cloudnative-pg
  - operators/external-secrets
  - operators/kyverno
  - operators/strimzi
  - storage/rook-ceph-operator