---
- name: Deploy visit demo applications
  hosts: control_plane[0]
  become: true
  gather_facts: false
  tasks:
    - name: Copy apps Flux stage to control plane
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../kubernetes/flux/clusters/dev/apps/"
        dest: /tmp/flux-apps/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Apply app Flux Kustomizations
      ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply --kustomize /tmp/flux-apps
      changed_when: true

    - name: Reconcile platform app policies Flux Kustomization
      ansible.builtin.command: flux reconcile kustomization platform-apps -n flux-system --timeout=15m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false

    - name: Reconcile visit-web Flux Kustomization
      ansible.builtin.command: flux reconcile kustomization app-visit-web -n flux-system --timeout=15m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false

    - name: Reconcile visit-processing Flux Kustomization
      ansible.builtin.command: flux reconcile kustomization app-visit-processing -n flux-system --timeout=15m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false
