---
- name: Deploy core platform services
  hosts: control_plane[0]
  become: true
  gather_facts: false
  tasks:
    - name: Wait for core Flux Kustomizations readiness
      ansible.builtin.command: >-
        kubectl --kubeconfig /etc/kubernetes/admin.conf -n flux-system wait
        --for=condition=Ready --timeout=5m
        kustomizations.kustomize.toolkit.fluxcd.io/{{ item }}
      loop:
        - platform-core
        - platform-data-ceph
      changed_when: false

    - name: Copy core platform Flux stage to control plane
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../kubernetes/flux/clusters/dev/core-platform/"
        dest: /tmp/flux-core-platform/
        owner: root
        group: root
        mode: "0644"
        directory_mode: "0755"

    - name: Apply core platform Flux Kustomizations
      ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply --kustomize /tmp/flux-core-platform
      changed_when: true

    - name: Reconcile observability Flux Kustomization
      ansible.builtin.command: flux reconcile kustomization platform-observability -n flux-system --timeout=20m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false

    - name: Reconcile ingress Flux Kustomization
      ansible.builtin.command: flux reconcile kustomization platform-ingress -n flux-system --timeout=15m --kubeconfig /etc/kubernetes/admin.conf
      changed_when: false
