---
base_packages:
  - apt-transport-https
  - ca-certificates
  - chrony
  - curl
  - gnupg
  - jq
  - software-properties-common
  - unzip

base_kernel_modules:
  - overlay
  - br_netfilter

base_sysctl:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"
