---
kubeadm_kubernetes_version: stable
kubeadm_control_plane_endpoint: "{{ kube_api_internal_endpoint | default(hostvars[groups['control_plane'][0]].private_ip ~ ':6443') }}"
kubeadm_apiserver_cert_extra_sans: >-
  {{
    [kube_api_public_endpoint]
    if (kube_api_public_endpoint is defined and (kube_api_public_endpoint | trim | length) > 0)
    else []
  }}
kubeadm_pod_subnet: 192.168.0.0/16
kubeadm_service_subnet: 10.96.0.0/12
kubeadm_cri_socket: unix:///run/containerd/containerd.sock
kubeadm_upload_certs: true
kube_proxy_metrics_bind_address: 0.0.0.0:10249
