apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-platform-apps.yaml
  - kustomization-app-visit-web.yaml
  - kustomization-app-visit-processing.yaml
  - kustomization-app-visit-loadgen.yaml
