apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-visit-loadgen
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: app-visit-web
    - name: app-visit-processing
  sourceRef:
    kind: GitRepository
    name: dev-repo
  path: ./kubernetes/apps/dev/visit-loadgen
  prune: true
  wait: true
  timeout: 15m
