apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-processor-kafka-tls
  namespace: visit-processing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-data-kafka
  target:
    name: visit-processor-kafka-tls
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: kafka-cluster-ca-cert
        property: ca.crt
    - secretKey: user.crt
      remoteRef:
        key: visit-processor
        property: user.crt
    - secretKey: user.key
      remoteRef:
        key: visit-processor
        property: user.key
