apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: visit-demo-db
  namespace: visit-processing
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: visit-demo-db
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dev/apps/visit-demo/processing
        property: DB_PASSWORD
