apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: visit-processor
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: visit-processing
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/visit-processor
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: dev-repo
  values:
    imagePullSecrets:
      - name: ghcr-pull
    image:
      repository: ghcr.io/martin3398/visit-processor # {"$imagepolicy": "flux-system:visit-processor:name"}
      tag: 20260712181708-01901af3 # {"$imagepolicy": "flux-system:visit-processor:tag"}
