apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: visit-loadgen
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: visit-loadgen
  install:
    createNamespace: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/visit-loadgen
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: dev-repo
  values:
    imagePullSecrets:
      - name: ghcr-pull
    image:
      repository: ghcr.io/martin3398/visit-loadgen # {"$imagepolicy": "flux-system:visit-loadgen:name"}
      tag: 20260825193250-3a80e0ee # {"$imagepolicy": "flux-system:visit-loadgen:tag"}
    config:
      mode: random
      fixedBand: below
      targetBaseUrl: http://visit-web-visit-gateway.visit-web.svc/api/v1
