apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - kustomization-infrastructure-core.yaml
  - kustomization-infrastructure-scheduling.yaml
  - kustomization-infrastructure-data-ceph.yaml
  - kustomization-infrastructure-security.yaml
  - kustomization-infrastructure-data-postgres.yaml
  - kustomization-infrastructure-data-kafka.yaml
  - kustomization-infrastructure-observability.yaml
  - kustomization-infrastructure-ingress.yaml
  - apps
