apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-loadgen.yaml
  - helmrelease-visit-loadgen.yaml
  - imagerepository-visit-loadgen.yaml
  - imagepolicy-visit-loadgen.yaml
  - imageupdateautomation.yaml
